repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=500']
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.9.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports
        types: [python]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: [python]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.9.2
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        types: [python]
        additional_dependencies: [
            flake8-alfred,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-eradicate,
            flake8-print,
            flake8-pytest-style,
            flake8-todo,
            flake8-unused-arguments,
            pep8-naming,
            pydocstyle,
            Pygments,
        ]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.7
  hooks:
    -   id: nbqa-black
    -   id: nbqa-pyupgrade
    -   id: nbqa-isort
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
    -   id: doc8
-   repo: https://github.com/econchick/interrogate
    rev: 1.3.2
    hooks:
    -   id: interrogate
        args: [
            -v,
            --fail-under=78,
            --generate-badge=docs/source/_static/images/interrogate_badge.svg,
            src,
        ]
        pass_filenames: false
-   repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
    -   id: codespell
        exclude: \.ipynb
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
