repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.0.0
    hooks:
    -   id: reorder-python-imports
        types: [python]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        types: [python]
