coverage:
  range: 50...100
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 0%

ignore:
  - ".tox/**/*"
  - "setup.py"
  - "versioneer.py"
  - "src/sid/_version.py"
