name: sid

channels:
  - conda-forge
  - opensourceeconomics

dependencies:
  - python >=3.6
  - pip

  - anaconda-client
  - bump2version
  - conda-build
  - conda-verify

  - black
  - bokeh
  - dask
  - estimagic
  - fastparquet
  - hypothesis
  - jupyterlab
  - nbsphinx
  - numba >=0.48
  - numpy
  - pandas >=1
  - panel
  - pdbpp
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-regressions
  - pytest-xdist
  - python-snappy
  - scipy
  - seaborn
  - snakeviz
  - tqdm
  - virtualenv =20.0.33

  - sphinx
  - sphinx-copybutton
  - sphinx-autoapi
