name: sid

channels:
  - conda-forge
  - opensourceeconomics
  - nodefaults

dependencies:
  - python >=3.6
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - bokeh
  - dask
  - fastparquet !=0.6.1
  - holoviews
  - numba >=0.48
  - pandas >=1
  - python-snappy
  - seaborn
  - tqdm

  # Misc
  - black
  - estimagic
  - hypothesis
  - jupyterlab
  - pdbpp
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-regressions
  - pytest-xdist
  - snakeviz
  - tox-conda

  # Documentation
  - furo
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-panels
