name: sid

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:
  - python<3.9
  - pip

  - anaconda-client
  - conda-build
  - conda-verify

  - bokeh
  - dask
  - fastparquet
  - jupyterlab
  - nbsphinx
  - numba>=0.48
  - numpy
  - pandas>=1
  - panel
  - pdbpp
  - pre-commit
  - pytest
  - pytest-regressions
  - pytest-xdist
  - scipy
  - seaborn
  - snakeviz
  - pydata-sphinx-theme
  - python-snappy

  - sphinx
  - sphinx-copybutton
  - sphinx-autoapi

  # for bokeh png export
  - selenium
  - geckodriver
  - firefox

  # Jupyter Lab Formatter
  - black
  - jupyterlab_code_formatter
  - nodejs

  - pip:
    - blackcellmagic
