name: sid

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:

  - python
  - pip

  - anaconda-client
  - conda-build
  - conda-verify

  - bokeh>=2
  - dask
  - fastparquet
  - jupyterlab
  - nbsphinx
  - numba>=0.48
  - numpy
  - pandas>=1,<1.1
  - panel>=0.9.2
  - pdbpp
  - pre-commit
  - pytest
  - pytest-regressions
  - pytest-xdist
  - scipy
  - seaborn>=0.10
  - sphinx
  - pydata-sphinx-theme
  - python-snappy
  - utilities>=0.2.6

  # for bokeh png export
  - selenium
  - geckodriver
  - firefox

  # Jupyter Lab Formatter
  - black
  - jupyterlab_code_formatter
  - nodejs

  - snakeviz
  - pip:
    - blackcellmagic
