name: sid

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:

  - python=3.7
  - pip=19.0.3
  - pandas>=1.0
  - numpy
  - scipy
  - seaborn>=0.10
  - jupyterlab
  - nbsphinx
  - pdbpp
  - sphinx
  - xlrd
  - conda-build
  - anaconda-client
  - panel>=0.9.2
  - bokeh>=2.0
  - numba>=0.48.0
  - estimagic>=0.0.29
  - pytest
  - utilities>=0.2.6
  - snakeviz
  - pip:
    - black
    - blackcellmagic
    - pre-commit
    - yummy_sphinx_theme
