{% set data = load_setup_py_data() %}

package:
  name: sid
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff. However, it only captures
  # committed code, so pay attention.
  git_url: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
  host:
    - python >=3.6,<3.9

  run:
    - python >=3.6,<3.9
    - bokeh
    - dask
    - fastparquet
    - numba >=0.48
    - numpy
    - pandas >=1
    - python-snappy
    - seaborn

test:
  requires:
    - pytest
    - pytest-regressions
    - pytest-xdist
  source_files:
    - tox.ini
    - tests
  imports:
    - sid
  commands:
    - pytest -m "not optional"

about:
  home: https://github.com/covid-19-impact-lab/sid
  license: MIT
  summary: Simulate the spread of COVID-19 with different policies.
