channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >= 3.6

  # Sphinx dependencies.
  - furo
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-panels

  # Package dependencies.
  - bokeh
  - dask
  - fastparquet
  - numba >=0.48
  - pandas >=1
  - python-snappy
  - seaborn
  - tqdm
