channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >= 3.6
  - pip
  - setuptools_scm
  - toml
  - ipykernel

  # Sphinx dependencies.
  - furo
  - ipython
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-panels

  # Package dependencies.
  - bokeh
  - dask
  - fastparquet !=0.6.1
  - holoviews
  - numba >=0.48
  - pandas >=1
  - python-snappy
  - seaborn
  - tqdm

  - pip:
    - ../
